// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDvJ6SAoHLBKQflrnJePbeaz7xSs5X-U',
    appId: '1:532395073386:web:bd2d4ef9bb224eb924cf13',
    messagingSenderId: '532395073386',
    projectId: 'binding-of-isaac-item-finder',
    authDomain: 'binding-of-isaac-item-finder.firebaseapp.com',
    storageBucket: 'binding-of-isaac-item-finder.appspot.com',
    measurementId: 'G-VR07CJ8GFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqtA5mm96Dvl-mSIaq1QHamuGPYjt17co',
    appId: '1:532395073386:android:cad3e4ffd9df930b24cf13',
    messagingSenderId: '532395073386',
    projectId: 'binding-of-isaac-item-finder',
    storageBucket: 'binding-of-isaac-item-finder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDweMiJ8Bk8DMQxiJioGjpSlFzK3ZJDou8',
    appId: '1:532395073386:ios:452903b583089ae824cf13',
    messagingSenderId: '532395073386',
    projectId: 'binding-of-isaac-item-finder',
    storageBucket: 'binding-of-isaac-item-finder.appspot.com',
    iosBundleId: 'com.example.bindingofisaacitemfinderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDweMiJ8Bk8DMQxiJioGjpSlFzK3ZJDou8',
    appId: '1:532395073386:ios:8dbdc1ec7c8c405e24cf13',
    messagingSenderId: '532395073386',
    projectId: 'binding-of-isaac-item-finder',
    storageBucket: 'binding-of-isaac-item-finder.appspot.com',
    iosBundleId: 'com.example.bindingofisaacitemfinderapp.RunnerTests',
  );
}
